# Generated by Django 4.0.6 on 2022-07-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thue', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='_id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='room',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='thue.product'),
        ),
    ]
